### ISSUE TITLE
Add missing <sys/select.h> header

### ISSUE THREAD

**Issue by ghost** [Nat-Lab/tapio#1]
My build environment may differ slightly: I need to include the <sys/select.h> header in order to compile tapio (using lib musl on Void Linux).

```diff
diff --git a/tapio.c b/tapio.c
index c82e47e..c41c106 100644
--- a/tapio.c
+++ b/tapio.c
@@ -6,6 +6,7 @@
 #include <string.h>
 #include <fcntl.h>

+#include <sys/select.h>
 #include <sys/socket.h>
 #include <sys/ioctl.h>
 #include <linux/if.h>
```

**Comment by magicnat** [comment]
`sys/select.h` are indeed required for `select` as per POSIX standard. I'll add it.
